spring:
  application:
    name: car-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.auth-url}/realms/${keycloak.realm}/protocol/openid-connect/certs # JSON Web Key URI to use to verify the JWT token.

  main:
    lazy-iniliation: false
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:test_22}
  rsocket:
    server:
      transport: tcp
      mapping-part: /rsocket
      port: 7001

server:
  port: ${SERVER_PORT:8081}

keycloak:
  realm: ${KEYCLOAK_REALM:myrealm}
  auth-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:7070}/auth

eureka:
  instance:
    metadataMap:
      tcp: ${spring.rsocket.server.port}
      rsocketPort: ${spring.rsocket.server.port}
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
